import os
import uuid
import zipfile
import io
import fitz  # PyMuPDF
from flask import Flask, request, jsonify, send_file, render_template, redirect
from werkzeug.utils import secure_filename

app = Flask(__name__)

# Vercel Serverless 环境使用 /tmp，本地开发使用项目目录
_IS_VERCEL = os.environ.get('VERCEL') == '1'
_BASE_DIR = '/tmp' if _IS_VERCEL else os.path.dirname(os.path.abspath(__file__))

app.config['UPLOAD_FOLDER'] = os.path.join(_BASE_DIR, 'uploads')
app.config['OUTPUT_FOLDER'] = os.path.join(_BASE_DIR, 'outputs')
app.config['MAX_CONTENT_LENGTH'] = 100 * 1024 * 1024  # 100MB

os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
os.makedirs(app.config['OUTPUT_FOLDER'], exist_ok=True)


class WatermarkRemover:
    """PDF 水印检测与去除引擎
    
    支持两种模式:
    1. PDF 结构层水印（文本/图片对象）
    2. 像素级水印（水印烧录在整页图片中，如 NotebookLM 导出的 PDF）
    """

    EXACT_WATERMARK_BRANDS = [
        'notebooklm', 'notebook lm', 'google notebooklm',
    ]

    WATERMARK_KEYWORDS = [
        'watermark', 'draft', 'confidential', 'sample', 'copy',
        'do not copy', 'unofficial', 'preview', 'demo', 'specimen',
        'not for distribution', 'internal use only', 'evaluation',
        '水印', '草稿', '机密', '样本', '副本', '仅供参考',
        '未经授权', '预览', '内部资料', '请勿外传',
        'generated by', '自动生成', 'powered by',
    ]

    def __init__(self, sensitivity='medium'):
        self.sensitivity = sensitivity
        self.config = {
            'low':    {'corner_pct': 0.12, 'inpaint_radius': 5},
            'medium': {'corner_pct': 0.15, 'inpaint_radius': 7},
            'high':   {'corner_pct': 0.20, 'inpaint_radius': 10},
        }[sensitivity]

    def remove_watermarks(self, input_path, output_path):
        doc = fitz.open(input_path)
        stats = {'pages': len(doc), 'text_removed': 0, 'image_removed': 0}

        is_image_pdf = self._is_image_based_pdf(doc)

        if is_image_pdf:
            for page_num in range(len(doc)):
                page = doc[page_num]
                if self._clean_page_pixel_watermark(doc, page):
                    stats['image_removed'] += 1
        else:
            for page_num in range(len(doc)):
                page = doc[page_num]
                t = self._remove_text_watermarks_structural(page)
                stats['text_removed'] += t

        doc.save(output_path, garbage=4, deflate=True, clean=True)
        doc.close()
        return stats

    def _is_image_based_pdf(self, doc):
        """检测是否为纯图片型 PDF（如 NotebookLM 导出）"""
        # 检查前 3 页
        check_pages = min(3, len(doc))
        image_pages = 0
        for i in range(check_pages):
            page = doc[i]
            text = page.get_text().strip()
            images = page.get_images(full=True)
            # 没有文本但有图片 → 图片型页面
            if not text and len(images) >= 1:
                image_pages += 1
        return image_pages >= check_pages * 0.8

    def _clean_page_pixel_watermark(self, doc, page):
        """简洁有效的逐页像素水印清除：扫描右下角固定区域，用背景色覆盖水印"""
        from PIL import Image, ImageFilter
        import numpy as np

        images = page.get_images(full=True)
        if not images:
            return False

        xref = images[0][0]
        img_info = doc.extract_image(xref)
        if not img_info:
            return False

        pil_img = Image.open(io.BytesIO(img_info["image"])).convert("RGB")
        img_np = np.array(pil_img)
        h, w, _ = img_np.shape

        # 扫描区域：底部 30px，右侧 250px
        scan_h, scan_w = 30, 250
        sx1, sy1 = w - scan_w, h - scan_h
        sx2, sy2 = w, h

        region = img_np[sy1:sy2, sx1:sx2].copy()

        # 背景色：找区域内最"空白"的行（前景最少），用它的中位数做背景
        # 先用区域右下角小块粗估背景
        corner = region[-5:, -5:, :].reshape(-1, 3)
        rough_bg = np.median(corner, axis=0)
        
        # 找最空白的几行
        best_rows = []
        for ri in range(region.shape[0]):
            row_diff = np.sqrt(np.sum((region[ri].astype(float) - rough_bg) ** 2, axis=1))
            fg_count = (row_diff > 20).sum()
            best_rows.append((fg_count, ri))
        best_rows.sort()
        
        # 用前景最少的 5 行做背景采样
        bg_pixels = []
        for _, ri in best_rows[:5]:
            bg_pixels.append(region[ri])
        bg_color = np.median(np.concatenate(bg_pixels, axis=0).reshape(-1, 3), axis=0)

        # 前景检测——直接覆盖所有非背景像素，不做行排除
        diff = np.sqrt(np.sum((region.astype(float) - bg_color) ** 2, axis=2))
        fg_mask = diff > 8  # 极低阈值确保覆盖所有水印痕迹

        if not np.any(fg_mask):
            return False

        # 膨胀 3px 覆盖抗锯齿
        mask_img = Image.fromarray((fg_mask * 255).astype(np.uint8))
        mask_img = mask_img.filter(ImageFilter.MaxFilter(size=3))
        final_mask = np.array(mask_img) > 128

        # 用 alpha 混合做精确覆盖
        alpha_img = Image.fromarray((final_mask * 255).astype(np.uint8))
        alpha_img = alpha_img.filter(ImageFilter.GaussianBlur(radius=1))
        alpha = np.array(alpha_img).astype(float) / 255.0

        fill = np.full_like(region, bg_color.astype(np.uint8))
        for c in range(3):
            region[:, :, c] = (
                alpha * fill[:, :, c].astype(float) +
                (1 - alpha) * region[:, :, c].astype(float)
            ).clip(0, 255).astype(np.uint8)

        img_np[sy1:sy2, sx1:sx2] = region

        # 写回 PDF
        cleaned_img = Image.fromarray(img_np)
        buf = io.BytesIO()
        cleaned_img.save(buf, format='PNG')
        new_pix = fitz.Pixmap(buf.getvalue())
        page.replace_image(xref, pixmap=new_pix)
        return True

    def _build_watermark_masks(self, doc, template):
        """每页独立构建水印掩码：模板区域内所有非背景像素，仅排除全宽横线边框"""
        from PIL import Image, ImageFilter
        import numpy as np

        tx1, ty1 = template['abs_x'], template['abs_y']
        tx2, ty2 = template['abs_x2'], template['abs_y2']
        rh, rw = ty2 - ty1, tx2 - tx1

        masks = []
        for pn in range(len(doc)):
            page = doc[pn]
            images = page.get_images(full=True)
            if not images:
                masks.append(None)
                continue
            xref = images[0][0]
            img_info = doc.extract_image(xref)
            if not img_info:
                masks.append(None)
                continue

            pil_img = Image.open(io.BytesIO(img_info["image"])).convert("RGB")
            img_np = np.array(pil_img)
            h, w, _ = img_np.shape

            region = img_np[max(0, ty1):min(h, ty2), max(0, tx1):min(w, tx2)]
            crh, crw = region.shape[0], region.shape[1]

            # 背景色：优先从下方和右侧采样（水印在右下角，这两侧最能反映水印区域背景）
            bg_samples = []
            band = 10
            # 下方优先
            if ty2 + band < h:
                bg_samples.append(img_np[ty2:ty2 + band, tx1:tx2].reshape(-1, 3))
            # 右侧
            if tx2 + band < w:
                bg_samples.append(img_np[ty1:ty2, tx2:tx2 + band].reshape(-1, 3))
            # 只有下方和右侧都不可用时才用上方和左侧
            if not bg_samples:
                if ty1 > band:
                    bg_samples.append(img_np[ty1 - band:ty1, tx1:tx2].reshape(-1, 3))
                if tx1 > band:
                    bg_samples.append(img_np[ty1:ty2, tx1 - band:tx1].reshape(-1, 3))

            if bg_samples:
                bg_color = np.median(np.concatenate(bg_samples, axis=0), axis=0)
            else:
                bg_color = np.array([245, 242, 231], dtype=float)

            # 前景检测
            diff = np.sqrt(np.sum((region[:crh, :crw].astype(float) - bg_color) ** 2, axis=2))
            fg_mask = diff > 15

            # 仅排除：横跨 >80% 宽度的行（明确是粗边框线）
            for ri in range(crh):
                if fg_mask[ri].sum() / max(crw, 1) > 0.8:
                    fg_mask[ri, :] = False

            # 膨胀 3px 覆盖抗锯齿
            mask_img = Image.fromarray((fg_mask * 255).astype(np.uint8))
            mask_img = mask_img.filter(ImageFilter.MaxFilter(size=3))
            final_mask = np.array(mask_img) > 128

            masks.append(final_mask)

        return masks

    def _detect_watermark_template(self, doc):
        """跨页分析，检测水印位置和模板"""
        from PIL import Image
        import numpy as np

        sample_pages = list(range(min(5, len(doc))))
        bottom_strips = []

        for page_num in sample_pages:
            page = doc[page_num]
            images = page.get_images(full=True)
            if not images:
                continue
            xref = images[0][0]
            img_data = doc.extract_image(xref)
            if not img_data:
                continue

            pil_img = Image.open(io.BytesIO(img_data["image"])).convert("RGB")
            w, h = pil_img.size
            strip_h = 60
            strip_w = 300
            strip = np.array(pil_img.crop((w - strip_w, h - strip_h, w, h)))
            bottom_strips.append({
                'page': page_num,
                'strip': strip,
                'full_size': (w, h),
                'origin': (w - strip_w, h - strip_h),
            })

        if len(bottom_strips) < 2:
            return None

        # 跨页比较
        ref = bottom_strips[0]['strip'].astype(float)
        similar = 0
        for other_info in bottom_strips[1:]:
            other = other_info['strip'].astype(float)
            if ref.shape == other.shape:
                if np.abs(ref - other).mean() < 40:
                    similar += 1

        if similar == 0:
            return None

        # 多页叠加分析：找出跨页稳定出现的前景像素
        all_fg_masks = []
        for info in bottom_strips:
            s = info['strip']
            bg = np.median(s[0:3, :, :].reshape(-1, 3), axis=0)
            d = np.sqrt(np.sum((s.astype(float) - bg) ** 2, axis=2))
            all_fg_masks.append(d > 25)

        # 在 >=60% 的页面中都是前景的像素 = 稳定水印像素
        sh, sw = all_fg_masks[0].shape
        stable_mask = np.zeros((sh, sw), dtype=int)
        for m in all_fg_masks:
            stable_mask += m.astype(int)
        threshold = max(2, int(len(all_fg_masks) * 0.6))
        wm_mask = stable_mask >= threshold

        # 排除边框线：横跨 >30% 宽度的行 = 横边框
        for ri in range(sh):
            if wm_mask[ri].sum() / sw > 0.3:
                wm_mask[ri, :] = False
        # 排除纵跨 >30% 高度的列 = 竖边框
        for ci in range(sw):
            if wm_mask[:, ci].sum() / sh > 0.3:
                wm_mask[:, ci] = False
        # 排除前景像素过少的孤立行 (<8 像素大概率是噪点/边框残留)
        for ri in range(sh):
            if 0 < wm_mask[ri].sum() < 8:
                wm_mask[ri, :] = False

        fg_rows = np.where(np.any(wm_mask, axis=1))[0]
        fg_cols = np.where(np.any(wm_mask, axis=0))[0]

        if len(fg_rows) == 0 or len(fg_cols) == 0:
            return None

        origin = bottom_strips[0]['origin']
        full_size = bottom_strips[0]['full_size']
        bg_color = np.median(bottom_strips[0]['strip'][0:3, :, :].reshape(-1, 3), axis=0)

        # 紧凑 padding：只需 5px 即可
        pad = 5
        y1 = max(0, fg_rows.min() - pad)
        y2 = min(sh, fg_rows.max() + pad + 1)
        x1 = max(0, fg_cols.min() - pad)
        x2 = min(sw, fg_cols.max() + pad + 1)

        return {
            'abs_x': origin[0] + x1,
            'abs_y': origin[1] + y1,
            'abs_x2': origin[0] + x2,
            'abs_y2': origin[1] + y2,
            'full_size': full_size,
            'bg_color': tuple(int(c) for c in bg_color),
        }

    def _clean_page_image(self, doc, page, page_num, watermark_template, wm_pixel_mask):
        """清理单页图片中的水印，使用精确像素掩码"""
        from PIL import Image, ImageFilter
        import numpy as np

        images = page.get_images(full=True)
        if not images:
            return False

        xref = images[0][0]
        img_info = doc.extract_image(xref)
        if not img_info:
            return False

        pil_img = Image.open(io.BytesIO(img_info["image"])).convert("RGB")
        img_np = np.array(pil_img)
        h, w, _ = img_np.shape

        if wm_pixel_mask is None or not np.any(wm_pixel_mask):
            return False

        if not watermark_template:
            return False

        tx1 = max(0, watermark_template['abs_x'])
        ty1 = max(0, watermark_template['abs_y'])
        tx2 = min(w, watermark_template['abs_x2'])
        ty2 = min(h, watermark_template['abs_y2'])

        region = img_np[ty1:ty2, tx1:tx2]
        mask = wm_pixel_mask
        rh, rw = mask.shape[:2]

        # 确保尺寸匹配
        crh = min(rh, region.shape[0])
        crw = min(rw, region.shape[1])
        mask = mask[:crh, :crw]
        region = region[:crh, :crw]

        if not np.any(mask):
            return False

        # 采样本页局部背景色（优先下方和右侧）
        bg_samples = []
        band = 8
        if ty2 + band < h:
            bg_samples.append(img_np[ty2:ty2 + band, tx1:tx2].reshape(-1, 3))
        if tx2 + band < w:
            bg_samples.append(img_np[ty1:ty2, tx2:tx2 + band].reshape(-1, 3))
        if not bg_samples:
            if ty1 > band:
                bg_samples.append(img_np[ty1 - band:ty1, tx1:tx2].reshape(-1, 3))

        if bg_samples:
            bg_color = np.median(np.concatenate(bg_samples, axis=0), axis=0).astype(np.uint8)
        else:
            bg_color = np.array(watermark_template['bg_color'], dtype=np.uint8)

        # 用背景色精确替换水印像素
        # 先创建背景填充
        fill = np.full_like(region, bg_color)

        # 创建浮点 alpha 用于平滑混合（掩码边缘做轻微模糊）
        alpha_img = Image.fromarray((mask * 255).astype(np.uint8))
        alpha_img = alpha_img.filter(ImageFilter.GaussianBlur(radius=1))
        alpha = np.array(alpha_img).astype(float) / 255.0

        # 混合
        for c in range(3):
            region[:, :, c] = (
                alpha * fill[:, :, c].astype(float) +
                (1 - alpha) * region[:, :, c].astype(float)
            ).clip(0, 255).astype(np.uint8)

        img_np[ty1:ty1+crh, tx1:tx1+crw] = region

        # 写回 PDF
        cleaned_img = Image.fromarray(img_np)
        buf = io.BytesIO()
        cleaned_img.save(buf, format='PNG')
        new_pix = fitz.Pixmap(buf.getvalue())
        page.replace_image(xref, pixmap=new_pix)

        return True

    def _inpaint_region(self, img_np, x1, y1, x2, y2):
        """使用背景色整块覆盖水印区域，边缘做渐变过渡"""
        import numpy as np
        from PIL import Image, ImageFilter

        h, w, _ = img_np.shape

        # 采样周围背景色（取区域外围一圈像素的中位数）
        sample_band = 10
        bg_samples = []
        # 上方
        sy1 = max(0, y1 - sample_band)
        if sy1 < y1:
            bg_samples.append(img_np[sy1:y1, x1:x2].reshape(-1, 3))
        # 下方
        sy2 = min(h, y2 + sample_band)
        if sy2 > y2:
            bg_samples.append(img_np[y2:sy2, x1:x2].reshape(-1, 3))
        # 左侧
        sx1 = max(0, x1 - sample_band)
        if sx1 < x1:
            bg_samples.append(img_np[y1:y2, sx1:x1].reshape(-1, 3))
        # 右侧
        sx2 = min(w, x2 + sample_band)
        if sx2 > x2:
            bg_samples.append(img_np[y1:y2, x2:sx2].reshape(-1, 3))

        if not bg_samples:
            return False

        all_bg = np.concatenate(bg_samples, axis=0)
        bg_color = np.median(all_bg, axis=0).astype(np.uint8)

        # 检查是否有前景存在
        region = img_np[y1:y2, x1:x2]
        diff = np.sqrt(np.sum((region.astype(float) - bg_color.astype(float)) ** 2, axis=2))
        if not np.any(diff > 15):
            return False

        # === 核心策略：整块背景色填充 + 边缘渐变 === #
        
        # 扩展处理区域用于边缘过渡
        fade = 3  # 渐变边缘宽度（最小化对周围内容的影响）
        ex1 = max(0, x1 - fade)
        ey1 = max(0, y1 - fade)
        ex2 = min(w, x2 + fade)
        ey2 = min(h, y2 + fade)

        # 创建一个纯背景色的填充层
        fill_h = ey2 - ey1
        fill_w = ex2 - ex1
        fill_layer = np.full((fill_h, fill_w, 3), bg_color, dtype=np.uint8)

        # 创建 alpha 遮罩：中心=1.0, 边缘渐变到0
        alpha = np.zeros((fill_h, fill_w), dtype=float)
        # 水印核心区域在扩展区域中的位置
        iy1 = y1 - ey1
        iy2 = y2 - ey1
        ix1 = x1 - ex1
        ix2 = x2 - ex1

        # 核心区域全部为 1.0
        alpha[iy1:iy2, ix1:ix2] = 1.0

        # 边缘渐变
        # 上边缘
        for i in range(iy1):
            t = (i + 1) / (iy1 + 1)
            alpha[i, ix1:ix2] = np.maximum(alpha[i, ix1:ix2], t)
        # 下边缘
        for i in range(iy2, fill_h):
            t = (fill_h - i) / (fill_h - iy2 + 1)
            alpha[i, ix1:ix2] = np.maximum(alpha[i, ix1:ix2], t)
        # 左边缘
        for j in range(ix1):
            t = (j + 1) / (ix1 + 1)
            alpha[iy1:iy2, j] = np.maximum(alpha[iy1:iy2, j], t)
        # 右边缘
        for j in range(ix2, fill_w):
            t = (fill_w - j) / (fill_w - ix2 + 1)
            alpha[iy1:iy2, j] = np.maximum(alpha[iy1:iy2, j], t)

        # 对 alpha 做一次高斯模糊让过渡更自然
        alpha_img = Image.fromarray((alpha * 255).astype(np.uint8))
        alpha_img = alpha_img.filter(ImageFilter.GaussianBlur(radius=1))
        alpha = np.array(alpha_img).astype(float) / 255.0

        # 混合：原图 * (1-alpha) + 背景填充 * alpha
        original_region = img_np[ey1:ey2, ex1:ex2].copy()
        for c in range(3):
            original_region[:, :, c] = (
                alpha * fill_layer[:, :, c].astype(float) +
                (1 - alpha) * original_region[:, :, c].astype(float)
            ).clip(0, 255).astype(np.uint8)

        img_np[ey1:ey2, ex1:ex2] = original_region
        return True

    def _scan_and_clean_corners(self, img_np, w, h):
        """扫描四个角落寻找水印"""
        import numpy as np

        corner_pct = self.config['corner_pct']
        cw = int(w * corner_pct)
        ch = int(h * corner_pct)

        corners = [
            (w - cw, h - ch, w, h),  # 右下
            (0, h - ch, cw, h),      # 左下
            (w - cw, 0, w, ch),      # 右上
            (0, 0, cw, ch),          # 左上
        ]

        cleaned = False
        for (cx1, cy1, cx2, cy2) in corners:
            region = img_np[cy1:cy2, cx1:cx2]

            # 估计这个角落的背景色
            edge = np.concatenate([
                region[0, :, :],
                region[-1, :, :],
                region[:, 0, :],
                region[:, -1, :],
            ])
            bg = np.median(edge.reshape(-1, 3), axis=0)

            # 看是否有小块前景（水印）
            diff = np.sqrt(np.sum((region.astype(float) - bg) ** 2, axis=2))
            fg_ratio = np.mean(diff > 30)

            # 如果前景占 0.5% ~ 20%，可能是水印
            if 0.005 < fg_ratio < 0.20:
                self._inpaint_region(img_np, cx1, cy1, cx2, cy2)
                cleaned = True

        return cleaned

    # ------------------------------------------------------------------ #
    #  结构层文本水印（非图片型 PDF）
    # ------------------------------------------------------------------ #
    def _remove_text_watermarks_structural(self, page):
        removed = 0
        page_rect = page.rect
        page_area = page_rect.width * page_rect.height

        text_dict = page.get_text("dict", flags=fitz.TEXT_PRESERVE_WHITESPACE)
        watermark_areas = []

        for block in text_dict.get("blocks", []):
            if block["type"] != 0:
                continue
            for line in block.get("lines", []):
                for span in line.get("spans", []):
                    if self._is_structural_watermark(span, page_rect, page_area):
                        bbox = fitz.Rect(span["bbox"])
                        watermark_areas.append(bbox)

        for area in watermark_areas:
            expanded = area + (-4, -4, 4, 4)
            expanded = expanded & page_rect
            page.add_redact_annot(expanded, fill=(255, 255, 255))
            removed += 1

        if watermark_areas:
            page.apply_redactions()
        return removed

    def _is_structural_watermark(self, span, page_rect, page_area):
        text = span.get("text", "").strip()
        if not text:
            return False
        text_lower = text.lower().replace(' ', '')

        for brand in self.EXACT_WATERMARK_BRANDS:
            if brand.replace(' ', '') in text_lower:
                return True

        is_keyword = any(kw in text_lower for kw in self.WATERMARK_KEYWORDS)
        color = span.get("color", 0)
        r = (color >> 16) & 0xFF
        g = (color >> 8) & 0xFF
        b = color & 0xFF
        is_light = r > 180 and g > 180 and b > 180
        is_gray = abs(r - g) < 25 and abs(g - b) < 25 and r > 140
        size = span.get("size", 12)
        bbox = fitz.Rect(span["bbox"])

        score = 0
        if is_keyword: score += 3
        if is_light or is_gray: score += 2
        if size > 30: score += 2
        if size > 50: score += 3

        threshold = {'low': 5, 'medium': 3, 'high': 2}[self.sensitivity]
        return score >= threshold


def remove_pixel_watermark_from_image(input_path, output_path):
    """对单张图片进行像素级水印清除，复用 PDF 引擎的核心算法"""
    from PIL import Image, ImageFilter
    import numpy as np

    pil_img = Image.open(input_path).convert("RGB")
    img_np = np.array(pil_img)
    h, w, _ = img_np.shape

    # 右下角扫描区域（同 PDF 算法）
    scan_h, scan_w = 30, 250
    sy1, sx1 = h - scan_h, w - scan_w

    region = img_np[sy1:h, sx1:w].copy()

    # 智能背景采样
    corner = region[-5:, -5:, :].reshape(-1, 3)
    rough_bg = np.median(corner, axis=0)

    best_rows = []
    for ri in range(region.shape[0]):
        row_diff = np.sqrt(np.sum((region[ri].astype(float) - rough_bg) ** 2, axis=1))
        best_rows.append((( row_diff > 20).sum(), ri))
    best_rows.sort()

    bg_pixels = []
    for _, ri in best_rows[:5]:
        bg_pixels.append(region[ri])
    bg_color = np.median(np.concatenate(bg_pixels, axis=0).reshape(-1, 3), axis=0)

    diff = np.sqrt(np.sum((region.astype(float) - bg_color) ** 2, axis=2))
    fg_mask = diff > 8

    if not np.any(fg_mask):
        # 没有检测到水印，直接复制原图
        pil_img.save(output_path)
        return {'cleaned': False}

    mask_img = Image.fromarray((fg_mask * 255).astype(np.uint8))
    mask_img = mask_img.filter(ImageFilter.MaxFilter(size=3))
    final_mask = np.array(mask_img) > 128

    alpha_img = Image.fromarray((final_mask * 255).astype(np.uint8))
    alpha_img = alpha_img.filter(ImageFilter.GaussianBlur(radius=1))
    alpha = np.array(alpha_img).astype(float) / 255.0

    fill = np.full_like(region, bg_color.astype(np.uint8))
    for c in range(3):
        region[:, :, c] = (
            alpha * fill[:, :, c].astype(float) +
            (1 - alpha) * region[:, :, c].astype(float)
        ).clip(0, 255).astype(np.uint8)

    img_np[sy1:h, sx1:w] = region

    ext = os.path.splitext(output_path)[1].lower()
    fmt = 'JPEG' if ext in ('.jpg', '.jpeg') else 'PNG'
    save_kwargs = {'quality': 95} if fmt == 'JPEG' else {}
    Image.fromarray(img_np).save(output_path, format=fmt, **save_kwargs)
    return {'cleaned': True}


def export_pdf_to_images(pdf_path, output_dir, dpi=200, fmt='png'):
    """将 PDF 每页导出为图片"""
    doc = fitz.open(pdf_path)
    image_paths = []
    zoom = dpi / 72
    matrix = fitz.Matrix(zoom, zoom)

    for page_num in range(len(doc)):
        page = doc[page_num]
        pix = page.get_pixmap(matrix=matrix)
        img_path = os.path.join(output_dir, f'page_{page_num + 1:04d}.{fmt}')
        pix.save(img_path)
        image_paths.append(img_path)

    doc.close()
    return image_paths


# ==================== Blob 工具函数 ====================

def _blob_upload(file_path, blob_name):
    """上传文件到 Vercel Blob，返回 blob url"""
    token = os.environ.get('BLOB_READ_WRITE_TOKEN')
    if not token:
        raise RuntimeError(
            'BLOB_READ_WRITE_TOKEN 环境变量未设置。'
            '请在 Vercel Dashboard → Settings → Environment Variables 中添加该变量。'
        )
    import vercel_blob
    with open(file_path, 'rb') as f:
        resp = vercel_blob.put(blob_name, f.read(), multipart=True)
    if isinstance(resp, dict):
        return resp.get('url', '')
    return getattr(resp, 'url', '')


def _blob_delete(blob_url):
    """删除 Blob 中的文件"""
    try:
        import vercel_blob
        vercel_blob.delete([blob_url])
    except Exception:
        pass


# ==================== Flask 路由 ====================

@app.route('/')
def index():
    return render_template('index.html')


ALLOWED_PDF = {'.pdf'}
ALLOWED_IMAGE = {'.png', '.jpg', '.jpeg', '.webp', '.bmp'}
ALLOWED_ALL = ALLOWED_PDF | ALLOWED_IMAGE


# ---------- 分块上传接口 ----------
@app.route('/api/upload/chunk', methods=['POST'])
def upload_chunk():
    """接收文件分块，写入 /tmp 拼合。每块 < 4MB，绕过 Vercel 4.5MB 限制"""
    task_id  = request.form.get('task_id')
    filename = secure_filename(request.form.get('filename', ''))
    chunk_index = int(request.form.get('chunk_index', 0))
    total_chunks = int(request.form.get('total_chunks', 1))
    file_type = request.form.get('file_type', 'pdf')

    if not task_id or not filename or 'chunk' not in request.files:
        return jsonify({'error': '参数缺失'}), 400

    tmp_dir = os.path.join('/tmp' if _IS_VERCEL else app.config['UPLOAD_FOLDER'], task_id)
    os.makedirs(tmp_dir, exist_ok=True)

    chunk_path = os.path.join(tmp_dir, f'{filename}.part{chunk_index}')
    request.files['chunk'].save(chunk_path)

    # 所有分块到齐后合并
    if chunk_index + 1 == total_chunks:
        final_path = os.path.join(tmp_dir, filename)
        with open(final_path, 'wb') as outf:
            for i in range(total_chunks):
                part = os.path.join(tmp_dir, f'{filename}.part{i}')
                with open(part, 'rb') as pf:
                    outf.write(pf.read())
                os.remove(part)

        return jsonify({
            'task_id': task_id,
            'filename': filename,
            'file_type': file_type,
            'assembled': True,
            'message': '上传完成'
        })

    return jsonify({'task_id': task_id, 'chunk_index': chunk_index, 'assembled': False})


# ---------- 本地模式：直接上传到服务器 ----------
@app.route('/api/upload', methods=['POST'])
def upload_pdf():
    if 'file' not in request.files:
        return jsonify({'error': '未选择文件'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': '文件名为空'}), 400

    ext = os.path.splitext(file.filename.lower())[1]
    if ext not in ALLOWED_ALL:
        return jsonify({'error': '仅支持 PDF 和图片文件（PNG/JPG/WEBP）'}), 400

    filename = secure_filename(file.filename)
    base_name = os.path.splitext(filename)[0]
    task_id = f'{base_name}_{str(uuid.uuid4())[:6]}'
    task_dir = os.path.join(app.config['UPLOAD_FOLDER'], task_id)
    os.makedirs(task_dir, exist_ok=True)

    input_path = os.path.join(task_dir, filename)
    file.save(input_path)

    file_type = 'pdf' if ext == '.pdf' else 'image'
    return jsonify({
        'task_id': task_id,
        'filename': filename,
        'file_type': file_type,
        'message': '上传成功'
    })


# ---------- 处理：本地 & Blob 双模式 ----------
@app.route('/api/process', methods=['POST'])
def process_pdf():
    data = request.json or {}
    sensitivity = data.get('sensitivity', 'medium')

    # ---- Vercel 分块上传模式 ----
    blob_url = data.get('blob_url')         # 兼容旧字段（保留）
    chunk_assembled = data.get('assembled') # 分块拼合完成标志
    if chunk_assembled or blob_url:
        filename = data.get('filename', 'file.pdf')
        ext = os.path.splitext(filename.lower())[1]
        file_type = 'pdf' if ext == '.pdf' else 'image'
        task_id = data.get('task_id', str(uuid.uuid4())[:8])

        tmp_dir = f'/tmp/{task_id}' if _IS_VERCEL else os.path.join(app.config['UPLOAD_FOLDER'], task_id)
        input_path  = os.path.join(tmp_dir, filename)
        output_name = f'clean_{filename}'
        output_path = os.path.join(tmp_dir, output_name)

        try:
            if not os.path.exists(input_path):
                return jsonify({'error': '文件未找到，请重新上传'}), 404

            if file_type == 'pdf':
                remover = WatermarkRemover(sensitivity=sensitivity)
                stats = remover.remove_watermarks(input_path, output_path)
            else:
                result = remove_pixel_watermark_from_image(input_path, output_path)
                stats = {'pages': 1, 'text_removed': 0,
                         'image_removed': 1 if result['cleaned'] else 0}

            # 上传结果到 Blob
            result_url = ''
            page_urls = []
            if _IS_VERCEL:
                blob_name = f'outputs/{task_id}/{output_name}'
                result_url = _blob_upload(output_path, blob_name)

                # 渲染所有页为预览图上传 Blob
                if file_type == 'pdf':
                    try:
                        import vercel_blob as vb
                        doc_prev = fitz.open(output_path)
                        for pi in range(len(doc_prev)):
                            pix = doc_prev[pi].get_pixmap(matrix=fitz.Matrix(1.5, 1.5))
                            png_bytes = pix.tobytes("png")
                            resp = vb.put(f'outputs/{task_id}/preview_p{pi+1}.png', png_bytes)
                            url = resp.get('url', '') if isinstance(resp, dict) else getattr(resp, 'url', '')
                            page_urls.append(url)
                        doc_prev.close()
                    except Exception as e:
                        app.logger.warning(f'Preview upload failed: {e}')
                else:
                    page_urls = [result_url]

            return jsonify({
                'task_id': task_id,
                'filename': filename,
                'file_type': file_type,
                'stats': stats,
                'result_url': result_url,
                'page_urls': page_urls,
                'message': '处理完成'
            })
        except Exception as e:
            return jsonify({'error': f'处理失败: {str(e)}'}), 500

    # ---- 本地模式 ----
    task_id = data.get('task_id')
    filename = data.get('filename')

    if not task_id or not filename:
        return jsonify({'error': '参数缺失'}), 400

    task_dir = os.path.join(app.config['UPLOAD_FOLDER'], task_id)
    input_path = os.path.join(task_dir, filename)

    if not os.path.exists(input_path):
        return jsonify({'error': '文件不存在'}), 404

    output_dir = os.path.join(app.config['OUTPUT_FOLDER'], task_id)
    os.makedirs(output_dir, exist_ok=True)

    ext = os.path.splitext(filename.lower())[1]

    try:
        if ext == '.pdf':
            output_pdf = os.path.join(output_dir, f'clean_{filename}')
            remover = WatermarkRemover(sensitivity=sensitivity)
            stats = remover.remove_watermarks(input_path, output_pdf)
            return jsonify({
                'task_id': task_id, 'filename': filename,
                'file_type': 'pdf', 'stats': stats, 'message': '处理完成'
            })
        else:
            output_image = os.path.join(output_dir, f'clean_{filename}')
            result = remove_pixel_watermark_from_image(input_path, output_image)
            return jsonify({
                'task_id': task_id, 'filename': filename,
                'file_type': 'image',
                'stats': {'pages': 1, 'text_removed': 0,
                          'image_removed': 1 if result['cleaned'] else 0},
                'message': '处理完成'
            })
    except Exception as e:
        return jsonify({'error': f'处理失败: {str(e)}'}), 500


@app.route('/api/blob_preview/<task_id>/<int:page_num>')
def blob_preview(task_id, page_num):
    """Vercel 模式：渲染 PDF 指定页返回 PNG，支持从 Blob URL 下载"""
    blob_url = request.args.get('blob_url')
    pdf_path = _ensure_pdf(task_id, blob_url)
    if not pdf_path:
        return jsonify({'error': '文件不存在，请重新处理'}), 404

    try:
        doc = fitz.open(pdf_path)
        total = len(doc)
        if page_num < 1 or page_num > total:
            doc.close()
            return jsonify({'error': '页码超出范围'}), 400
        pix = doc[page_num - 1].get_pixmap(matrix=fitz.Matrix(1.5, 1.5))
        img_data = pix.tobytes("png")
        doc.close()
        return send_file(io.BytesIO(img_data), mimetype='image/png',
                         headers={'X-Total-Pages': str(total)})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/api/preview/<task_id>/<int:page_num>')
def preview_page(task_id, page_num):
    """预览指定页面（PDF 或图片）"""
    output_dir = os.path.join(app.config['OUTPUT_FOLDER'], task_id)

    # 优先查找处理后的图片文件
    for ext in ('.png', '.jpg', '.jpeg', '.webp', '.bmp'):
        for fname in os.listdir(output_dir):
            if fname.startswith('clean_') and fname.lower().endswith(ext):
                img_path = os.path.join(output_dir, fname)
                return send_file(img_path, mimetype=f'image/{ext.lstrip(".")}')

    # 否则找 PDF
    pdf_files = [f for f in os.listdir(output_dir) if f.endswith('.pdf')]
    if not pdf_files:
        return jsonify({'error': '未找到处理后的文件'}), 404

    pdf_path = os.path.join(output_dir, pdf_files[0])
    doc = fitz.open(pdf_path)

    if page_num < 1 or page_num > len(doc):
        doc.close()
        return jsonify({'error': '页码超出范围'}), 400

    page = doc[page_num - 1]
    pix = page.get_pixmap(matrix=fitz.Matrix(1.5, 1.5))
    img_data = pix.tobytes("png")
    doc.close()

    return send_file(io.BytesIO(img_data), mimetype='image/png')


@app.route('/api/export/image/<task_id>')
def export_image_file(task_id):
    """导出去水印后的图片文件"""
    task_dir = _get_task_dir(task_id)
    for ext in ('.png', '.jpg', '.jpeg', '.webp', '.bmp'):
        for fname in os.listdir(task_dir):
            if fname.startswith('clean_') and fname.lower().endswith(ext):
                fpath = os.path.join(task_dir, fname)
                mime = 'image/jpeg' if ext in ('.jpg', '.jpeg') else f'image/{ext.lstrip(".")}'
                return send_file(fpath, as_attachment=True, download_name=fname, mimetype=mime)
    return jsonify({'error': '未找到处理后的图片'}), 404




@app.route('/api/page_count/<task_id>')
def page_count(task_id):
    """获取页数"""
    import glob
    task_dir = _get_task_dir(task_id)
    pdf_files = glob.glob(os.path.join(task_dir, 'clean_*.pdf'))
    if not pdf_files:
        output_dir = os.path.join(app.config['OUTPUT_FOLDER'], task_id)
        if os.path.isdir(output_dir):
            pdf_files = [os.path.join(output_dir, f)
                         for f in os.listdir(output_dir) if f.endswith('.pdf')]
    if not pdf_files:
        return jsonify({'error': '未找到文件'}), 404

    doc = fitz.open(pdf_files[0])
    count = len(doc)
    doc.close()
    return jsonify({'count': count})


def _get_task_dir(task_id):
    """获取 task 目录，Vercel 用 /tmp，本地用 OUTPUT_FOLDER"""
    if _IS_VERCEL:
        return f'/tmp/{task_id}'
    return os.path.join(app.config['OUTPUT_FOLDER'], task_id)


def _ensure_pdf(task_id, blob_url=None):
    """确保本地有 PDF 文件：优先 /tmp，否则从 Blob 下载"""
    import glob
    import requests as req_lib
    task_dir = _get_task_dir(task_id)
    pdf_files = glob.glob(os.path.join(task_dir, 'clean_*.pdf'))
    if pdf_files:
        return pdf_files[0]
    # 兼容本地模式
    output_dir = os.path.join(app.config['OUTPUT_FOLDER'], task_id)
    if os.path.isdir(output_dir):
        local = [os.path.join(output_dir, f)
                 for f in os.listdir(output_dir) if f.endswith('.pdf')]
        if local:
            return local[0]
    # 从 Blob 下载
    if blob_url:
        os.makedirs(task_dir, exist_ok=True)
        resp = req_lib.get(blob_url, timeout=60)
        resp.raise_for_status()
        pdf_path = os.path.join(task_dir, 'clean_downloaded.pdf')
        with open(pdf_path, 'wb') as f:
            f.write(resp.content)
        return pdf_path
    return None


@app.route('/api/export/pdf/<task_id>')
def export_pdf(task_id):
    """导出去水印后的 PDF"""
    blob_url = request.args.get('blob_url')
    if blob_url:
        return redirect(blob_url)
    pdf_path = _ensure_pdf(task_id)
    if not pdf_path:
        return jsonify({'error': '未找到文件'}), 404
    return send_file(pdf_path, as_attachment=True,
                     download_name=os.path.basename(pdf_path))


@app.route('/api/export/images/<task_id>')
def export_images(task_id):
    """导出为图片（ZIP 打包，每页一张）"""
    dpi = request.args.get('dpi', 200, type=int)
    fmt = request.args.get('format', 'png')
    blob_url = request.args.get('blob_url')

    if fmt not in ('png', 'jpg', 'jpeg'):
        fmt = 'png'

    task_dir = _get_task_dir(task_id)
    pdf_path = _ensure_pdf(task_id, blob_url)
    if not pdf_path:
        return jsonify({'error': '未找到文件'}), 404

    img_dir = os.path.join(task_dir, 'images')
    os.makedirs(img_dir, exist_ok=True)

    image_paths = export_pdf_to_images(pdf_path, img_dir, dpi=dpi, fmt=fmt)

    # 打包成 ZIP
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        for img_path in image_paths:
            zf.write(img_path, os.path.basename(img_path))

    zip_buffer.seek(0)
    base_name = os.path.splitext(os.path.basename(pdf_path))[0]
    return send_file(
        zip_buffer,
        mimetype='application/zip',
        as_attachment=True,
        download_name=f'{base_name}_images.zip'
    )


@app.route('/api/export/longimage/<task_id>')
def export_long_image(task_id):
    """将所有页面垂直拼接成一张长图导出"""
    from PIL import Image as PILImage

    dpi = request.args.get('dpi', 200, type=int)
    fmt = request.args.get('format', 'png')
    blob_url = request.args.get('blob_url')
    if fmt not in ('png', 'jpg', 'jpeg'):
        fmt = 'png'

    pdf_path = _ensure_pdf(task_id, blob_url)
    if not pdf_path:
        return jsonify({'error': '未找到文件'}), 404

    # 逐页渲染为像素图
    doc = fitz.open(pdf_path)
    zoom = dpi / 72
    matrix = fitz.Matrix(zoom, zoom)
    page_images = []
    for page_num in range(len(doc)):
        page = doc[page_num]
        pix = page.get_pixmap(matrix=matrix)
        img = PILImage.open(io.BytesIO(pix.tobytes("png"))).convert("RGB")
        page_images.append(img)
    doc.close()

    if not page_images:
        return jsonify({'error': '无页面可合并'}), 500

    # 以最大宽度为准，垂直拼接
    max_width = max(img.width for img in page_images)
    total_height = sum(img.height for img in page_images)

    long_img = PILImage.new("RGB", (max_width, total_height), (255, 255, 255))
    y_offset = 0
    for img in page_images:
        # 宽度不足时居中
        x_offset = (max_width - img.width) // 2
        long_img.paste(img, (x_offset, y_offset))
        y_offset += img.height

    buf = io.BytesIO()
    save_fmt = 'JPEG' if fmt in ('jpg', 'jpeg') else 'PNG'
    save_kwargs = {'quality': 90} if save_fmt == 'JPEG' else {}
    long_img.save(buf, format=save_fmt, **save_kwargs)
    buf.seek(0)

    base_name = os.path.splitext(os.path.basename(pdf_path))[0]
    ext = 'jpg' if save_fmt == 'JPEG' else 'png'
    mimetype = 'image/jpeg' if save_fmt == 'JPEG' else 'image/png'
    return send_file(
        buf,
        mimetype=mimetype,
        as_attachment=True,
        download_name=f'{base_name}_long.{ext}'
    )


if __name__ == '__main__':
    app.run(debug=True, port=5000)
